### ISSUE TITLE
Changes requested for AppCenter

### ISSUE THREAD

**Issue by cassidyjames** [albe-rosado/Hujing#29]
Thanks for submitting your app! I have a couple of changes to request:

- [x] It needs to depend on or include Flatpak in order to be distributed through AppCenter; otherwise, users install it and cannot do anything with flatpakref files. (They get `Error: Failed to execute child process “flatpak” (No such file or directory)` in the Terminal)
- [x] You should register your app with flatpakref MIME type so opening one from the web or local system automatically opens Hujing. Right now, users have to open your app _first_, then navigate to the flatpakref file.

Once you've addressed these items, please make a new release on GitHub and resubmit your app to AppCenter. Thanks again!

**Comment by albe-rosado** [comment]
Thanks Cassidy,  good to know. I'm working on the missing features and will
make another release soon, thank you for your support.
Regards, Alberto

**Comment by cassidyjames** [comment]
@albe-rosado thanks for taking the time to update and re-release your app for AppCenter. However, we've had to request changes for it as well.

https://github.com/albe-rosado/Hujing/compare/v0.1.23...v0.1.29#diff-4c24823d6727382406a3e88f19f57b15R190

As you'll find [in the wiki](https://github.com/elementary/houston/wiki/Before-You-Publish#technical-requirements):

>Your app must not attempt to modify, replace, or append software sources on the target system.

This includes the Flatpak PPA from Launchpad; adding a third party software source is not considered secure, and is giving root access to users' machines to the maintainer of that repository.

For Flatpak, I wonder if waiting to release the app for Juno would make the most sense; Flatpak is included in the repositories, and you can use standard Debian packaging to depend on it instead of manually installing it or adding PPAs in the middle of your app.

**Comment by albe-rosado** [comment]
Well, I guess will have to wait for Juno then, thanks Cassidy.

**Comment by albe-rosado** [comment]
Flatpak is not included in the repos on elementary or Ubuntu, so depending on it will fail when building.

**Comment by cassidyjames** [comment]
@albe-rosado Flatpak is included in the repos as of Ubuntu 18.04 and elementary OS 5.0 Juno. If you're targeting 16.04/Loki, I suppose you could do something like what @davidmhewitt does with [Torrential](https://github.com/davidmhewitt/torrential) and Transmission, and use a git submodule for your dependency. I'm not 100% sure how that works, but David might be able to give you pointers. The best bet, however, is likely waiting for the Juno beta and building your app for 18.04/Juno.

**Comment by albe-rosado** [comment]
Cool
